# Test Environment Configuration
spring:
  application:
    name: task-management-api-test

  # MongoDB Test Configuration (Uses embedded MongoDB via Testcontainers)
  data:
    mongodb:
      uri: mongodb://localhost:27017/taskdb-test

# Server Configuration
server:
  port: 0  # Random port for testing

# Logging Configuration (Minimal for tests)
logging:
  level:
    root: ERROR
    com.haithem.taskmanagemnt: INFO

# Springdoc OpenAPI Configuration
springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    enabled: false

# Management Endpoints
management:
  endpoints:
    web:
      exposure:
        include: health

